# Generated by Django 3.1.6 on 2021-04-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescueapp', '0002_rescueclass_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescueclass',
            name='des',
        ),
        migrations.RemoveField(
            model_name='rescueclass',
            name='email',
        ),
        migrations.AddField(
            model_name='rescueclass',
            name='city',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='rescueclass',
            name='lama',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='rescueclass',
            name='pin',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='rescueclass',
            name='state',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='rescueclass',
            name='strt',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
