# Generated by Django 3.1.6 on 2021-04-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donateclass',
            options={'get_latest_by': 'id'},
        ),
    ]
