# Generated by Django 3.1.6 on 2021-04-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportus', '0002_auto_20210430_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donateclass',
            options={},
        ),
    ]
