# Generated by Django 3.1.6 on 2021-05-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportus', '0003_auto_20210430_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateclass',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donateclass',
            name='state',
        ),
        migrations.AddField(
            model_name='donateclass',
            name='add',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
